baseURL = "https://bpinaya.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Benjamin Pinaya"

defaultContentLanguage = "en"
# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"

hasCJKLanguage = false
copyright = "testtt"

# whether to use robots.txt
enableRobotsTXT = true

# whether to use git commit log
enableGitInfo = false

# whether to use emoji code
enableEmoji = true

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""

  [[menu.main]]
    weight = 2
    identifier = "teaching"
    pre = ""
    post = ""
    name = "Teaching"
    url = "/teaching/"
    title = ""

  [[menu.main]]
    weight = 3
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
  

  [[menu.main]]
    weight = 4
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""

  [[menu.main]]
    weight = 5
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "dark"
  # which hash function used for SRI, when empty, no SRI is used
  fingerprint = ""
  # date format
  dateFormat = "01-02-2006"
  # website title for Open Graph and Twitter Cards
  title = "Benjamin Pinaya"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Personal blog, toughts and projects of Benjamin Pinaya"
  # website images for Open Graph and Twitter Cards //Change
  images = ["/logo.png"]

  # Author config
  [params.author]
    name = "Benjamin Pinaya"
    email = "bpinaya@outlook.com"
    link = "bpinaya.com"

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Ben's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "<i class='far fa-robot fa-fw' aria-hidden='true'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ""
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2018
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false